<?php

namespace Database\Seeders;

use App\Models\UiText;
use Illuminate\Database\Seeder;

/**
 * Frontend-in statik mətnləri (az / en / ru).
 *
 * Bu siyahı React tərəfindəki `src/i18n/dictionary.js` faylı ilə eynidir —
 * default dəyərlər orada saxlanılır, bu seeder isə həmin açarları admin panelinə
 * çıxarır ki, super admin deploy etmədən mətnləri dəyişə bilsin.
 *
 * MÖVCUD sətirlərə TOXUNMUR (firstOrCreate) — admin redaktələri qorunur.
 * Yeni açar əlavə edildikdə sadəcə yenidən işlədin:
 *   php artisan db:seed --class=UiTextSeeder
 */
class UiTextSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->rows() as [$key, $group, $az, $en, $ru]) {
            UiText::firstOrCreate(
                ['key' => $key],
                ['group' => $group, 'value' => ['az' => $az, 'en' => $en, 'ru' => $ru]],
            );
        }
    }

    /** @return array<int, array{0:string,1:string,2:string,3:string,4:string}> */
    private function rows(): array
    {
        return [
            ['common.loading', 'common', 'Yüklənir...', 'Loading...', 'Загрузка...'],
            ['common.back', 'common', '← Geri', '← Back', '← Назад'],
            ['common.retry', 'common', 'Yenidən cəhd et', 'Try again', 'Повторить'],
            ['common.copy', 'common', '📋 Kopyala', '📋 Copy', '📋 Копировать'],
            ['common.copied', 'common', 'Kod kopyalandı!', 'Code copied!', 'Код скопирован!'],
            ['common.days_left', 'common', '{count} gün qalıb', '{count} days left', 'Осталось {count} дн.'],
            ['common.unlimited', 'common', 'limitsiz', 'unlimited', 'без лимита'],
            ['nav.stores', 'nav', 'Mağazalar', 'Stores', 'Магазины'],
            ['nav.coupons', 'nav', '🎟 Kuponlarım', '🎟 My coupons', '🎟 Мои купоны'],
            ['nav.subscription', 'nav', 'Abunəliyim', 'My subscription', 'Моя подписка'],
            ['nav.plans', 'nav', 'Paketlər', 'Plans', 'Тарифы'],
            ['nav.login', 'nav', 'Daxil ol', 'Log in', 'Войти'],
            ['nav.logout', 'nav', 'Çıxış', 'Log out', 'Выйти'],
            ['home.title', 'home', 'Oyna, Qazan! 🎉', 'Play & Win! 🎉', 'Играй и выигрывай! 🎉'],
            ['home.subtitle', 'home', 'Mağazanı seç, suallara cavab ver, real endirim kuponu qazan.', 'Pick a store, answer the questions and win a real discount coupon.', 'Выберите магазин, ответьте на вопросы и получите реальный купон на скидку.'],
            ['home.view_campaigns', 'home', 'Kampaniyalara bax →', 'View campaigns →', 'Смотреть кампании →'],
            ['home.empty_title', 'home', 'Hazırda aktiv mağaza yoxdur', 'No active stores right now', 'Сейчас нет активных магазинов'],
            ['home.empty_subtitle', 'home', 'Bir azdan yenidən yoxlayın.', 'Please check back soon.', 'Загляните чуть позже.'],
            ['store.not_found', 'store', 'Mağaza tapılmadı', 'Store not found', 'Магазин не найден'],
            ['store.back_to_stores', 'store', '← Mağazalara qayıt', '← Back to stores', '← К магазинам'],
            ['store.active_campaigns', 'store', '🎯 Aktiv kampaniyalar', '🎯 Active campaigns', '🎯 Активные кампании'],
            ['store.no_quiz', 'store', 'Bu mağazada hazırda aktiv kampaniya yoxdur.', 'This store has no active campaign right now.', 'В этом магазине сейчас нет активных кампаний.'],
            ['store.questions_count', 'store', '📋 {count} sual', '📋 {count} questions', '📋 {count} вопросов'],
            ['store.per_question', 'store', '⏱ {sec}s / sual', '⏱ {sec}s / question', '⏱ {sec}с / вопрос'],
            ['store.play_button', 'store', '🚀 Oyna', '🚀 Play', '🚀 Играть'],
            ['store.reward_tiered', 'store', '{count}+ düz cavab → {reward} qazan!', '{count}+ correct answers → win {reward}!', '{count}+ правильных ответов → {reward}!'],
            ['store.reward_flat', 'store', 'Keçid balını topla → {reward} qazan!', 'Reach the pass score → win {reward}!', 'Наберите проходной балл → {reward}!'],
            ['store.reward_default', 'store', 'Suallara cavab ver, endirim qazan!', 'Answer the questions and win a discount!', 'Отвечайте на вопросы и получайте скидку!'],
            ['play.ready_title', 'play', 'Quizə hazırsan?', 'Ready for the quiz?', 'Готовы к квизу?'],
            ['play.ready_desc', 'play', 'Hər suala vaxt limiti var — düşün, amma gecikmə! Düzgün cavablar sənə real endirim kuponu qazandırır. 💸', 'Every question has a time limit — think fast! Correct answers earn you a real discount coupon. 💸', 'На каждый вопрос есть время — думайте быстро! Правильные ответы дают реальный купон на скидку. 💸'],
            ['play.guest_note', 'play', 'ℹ️ Qeydiyyatsız oynaya bilərsən — kuponu almaq üçün sonda qeydiyyat lazım olacaq.', 'ℹ️ You can play without an account — registration is required only to claim the coupon.', 'ℹ️ Можно играть без регистрации — она нужна только для получения купона.'],
            ['play.start', 'play', '🚀 Başla', '🚀 Start', '🚀 Начать'],
            ['play.loading_questions', 'play', 'Suallar hazırlanır...', 'Preparing questions...', 'Готовим вопросы...'],
            ['play.checking_answers', 'play', 'Cavablar yoxlanılır...', 'Checking answers...', 'Проверяем ответы...'],
            ['play.error_title', 'play', 'Nəsə səhv getdi', 'Something went wrong', 'Что-то пошло не так'],
            ['play.question_of', 'play', 'Sual {current} / {total}', 'Question {current} / {total}', 'Вопрос {current} / {total}'],
            ['play.congrats', 'play', 'Təbriklər!', 'Congratulations!', 'Поздравляем!'],
            ['play.failed', 'play', 'Bu dəfə alınmadı', 'Not this time', 'В этот раз не вышло'],
            ['play.result', 'play', 'Nəticə:', 'Result:', 'Результат:'],
            ['play.correct_answers', 'play', 'düzgün cavab', 'correct answers', 'правильных ответов'],
            ['play.your_coupon', 'play', 'Endirim kuponun', 'Your discount coupon', 'Ваш купон на скидку'],
            ['play.discount_won', 'play', '{reward} endirim', '{reward} discount', 'скидка {reward}'],
            ['play.expires', 'play', 'Son istifadə: {date}', 'Valid until: {date}', 'Действует до: {date}'],
            ['play.copy_code', 'play', '📋 Kodu kopyala', '📋 Copy code', '📋 Скопировать код'],
            ['play.guest_won', 'play', '🎁 {reward} endirim qazandın!', '🎁 You won a {reward} discount!', '🎁 Вы выиграли скидку {reward}!'],
            ['play.guest_register_desc', 'play', 'Kuponunu əldə etmək üçün qeydiyyatdan keç — nəticən yadda saxlanılıb.', 'Register to claim your coupon — your result has been saved.', 'Зарегистрируйтесь, чтобы получить купон — результат сохранён.'],
            ['play.register_cta', 'play', 'Qeydiyyatdan keç → Kuponu al', 'Register → Claim coupon', 'Регистрация → Получить купон'],
            ['play.have_account', 'play', 'Hesabım var — daxil ol', 'I have an account — log in', 'У меня есть аккаунт — войти'],
            ['play.not_passed', 'play', 'Keçid balını toplaya bilmədin. Bir də cəhd et! 💪', 'You did not reach the pass score. Try again! 💪', 'Проходной балл не набран. Попробуйте ещё раз! 💪'],
            ['play.play_again', 'play', '🔄 Yenidən oyna', '🔄 Play again', '🔄 Играть снова'],
            ['play.back_to_store', 'play', '🏪 Mağazaya qayıt', '🏪 Back to store', '🏪 Вернуться в магазин'],
            ['play.sub_required_title', 'play', 'Abunəlik lazımdır', 'Subscription required', 'Нужна подписка'],
            ['play.sub_required_default', 'play', 'Quiz oynamaq üçün aktiv abunəliyiniz olmalıdır.', 'You need an active subscription to play the quiz.', 'Для игры нужна активная подписка.'],
            ['play.sub_view_plans', 'play', 'Paketlərə bax →', 'View plans →', 'Смотреть тарифы →'],
            ['play.sub_claim_desc', 'play', 'Kuponu əldə etmək üçün aktiv abunəliyin olmalıdır. Abunə olduqdan sonra nəticən avtomatik kupona çevriləcək.', 'You need an active subscription to claim the coupon. Once you subscribe, your result turns into a coupon automatically.', 'Для получения купона нужна активная подписка. После оформления результат автоматически станет купоном.'],
            ['play.sub_claim_cta', 'play', '💳 Abunə ol → Kuponu al', '💳 Subscribe → Claim coupon', '💳 Оформить → Получить купон'],
            ['coupons.title', 'coupons', '🎟 Kuponlarım', '🎟 My coupons', '🎟 Мои купоны'],
            ['coupons.empty', 'coupons', 'Hələ kuponun yoxdur', 'You have no coupons yet', 'У вас пока нет купонов'],
            ['coupons.empty_desc', 'coupons', 'Mağazalardan birini seç, quiz oyna və endirim qazan!', 'Pick a store, play a quiz and win a discount!', 'Выберите магазин, сыграйте в квиз и получите скидку!'],
            ['coupons.browse', 'coupons', 'Mağazalara bax →', 'Browse stores →', 'Смотреть магазины →'],
            ['coupons.expires', 'coupons', 'Son istifadə: {date}', 'Valid until: {date}', 'Действует до: {date}'],
            ['coupons.status.active', 'coupons', 'Aktiv', 'Active', 'Активен'],
            ['coupons.status.redeemed', 'coupons', 'İstifadə olunub', 'Redeemed', 'Использован'],
            ['coupons.status.expired', 'coupons', 'Müddəti bitib', 'Expired', 'Истёк'],
            ['coupons.status.revoked', 'coupons', 'Ləğv edilib', 'Revoked', 'Отменён'],
            ['discount.percent', 'discount', '{value}% endirim', '{value}% discount', 'скидка {value}%'],
            ['discount.amount', 'discount', '{value} AZN endirim', '{value} AZN discount', 'скидка {value} AZN'],
            ['auth.login_title', 'auth', 'Daxil ol', 'Log in', 'Вход'],
            ['auth.register_title', 'auth', 'Qeydiyyat', 'Sign up', 'Регистрация'],
            ['auth.welcome_title', 'auth', 'Xoş gəlmisən! 👋', 'Welcome! 👋', 'Добро пожаловать! 👋'],
            ['auth.welcome_desc', 'auth', 'Quiz oyna, düzgün cavab ver və sevdiyin mağazalardan real endirim kuponları qazan.', 'Play quizzes, answer correctly and win real discount coupons from your favourite stores.', 'Играйте в квизы, отвечайте правильно и получайте реальные купоны любимых магазинов.'],
            ['auth.join_title', 'auth', 'Aramıza qoşul! 🚀', 'Join us! 🚀', 'Присоединяйтесь! 🚀'],
            ['auth.join_desc', 'auth', 'Qeydiyyatdan keç, quiz oyna və sevdiyin mağazalardan endirim kuponları qazan.', 'Sign up, play quizzes and win discount coupons from your favourite stores.', 'Зарегистрируйтесь, играйте в квизы и получайте купоны любимых магазинов.'],
            ['auth.pending_title', 'auth', 'Kuponun səni gözləyir! 🎁', 'Your coupon is waiting! 🎁', 'Ваш купон ждёт! 🎁'],
            ['auth.pending_desc', 'auth', 'Quiz nəticən yadda saxlanılıb — qeydiyyatı tamamla, kuponun dərhal hesabına düşsün.', 'Your quiz result is saved — finish signing up and the coupon lands in your account.', 'Результат сохранён — завершите регистрацию, и купон появится в аккаунте.'],
            ['auth.no_account', 'auth', 'Hesabın yoxdur?', 'No account yet?', 'Нет аккаунта?'],
            ['auth.have_account', 'auth', 'Hesabın var?', 'Already have an account?', 'Уже есть аккаунт?'],
            ['auth.register_link', 'auth', 'Qeydiyyatdan keç', 'Sign up', 'Зарегистрироваться'],
            ['auth.login_link', 'auth', 'Daxil ol', 'Log in', 'Войти'],
            ['auth.fullname', 'auth', 'Ad Soyad', 'Full name', 'Имя и фамилия'],
            ['auth.fullname_placeholder', 'auth', 'Ayşən Mirzəyeva', 'John Smith', 'Иван Иванов'],
            ['auth.phone', 'auth', 'Telefon nömrəsi', 'Phone number', 'Номер телефона'],
            ['auth.password', 'auth', 'Şifrə', 'Password', 'Пароль'],
            ['auth.submit_login', 'auth', 'Daxil ol', 'Log in', 'Войти'],
            ['auth.submit_register', 'auth', 'Qeydiyyatdan keç', 'Sign up', 'Зарегистрироваться'],
            ['auth.intro_play', 'auth', 'Oyna', 'Play', 'Играй'],
            ['auth.intro_answer', 'auth', 'Cavabla', 'Answer', 'Отвечай'],
            ['auth.intro_win', 'auth', 'Qazan', 'Win', 'Выигрывай'],
            ['validation.name_required', 'validation', 'Ad Soyad boş ola bilməz.', 'Full name is required.', 'Укажите имя и фамилию.'],
            ['validation.password_required', 'validation', 'Şifrə boş ola bilməz.', 'Password is required.', 'Введите пароль.'],
            ['validation.password_min', 'validation', 'Şifrə minimum 6 simvol olmalıdır.', 'Password must be at least 6 characters.', 'Пароль должен быть не короче 6 символов.'],
            ['validation.phone_required', 'validation', 'Telefon nömrəsi boş ola bilməz.', 'Phone number is required.', 'Введите номер телефона.'],
            ['validation.phone_invalid', 'validation', 'Telefon nömrəsi düzgün formatda deyil.', 'Invalid phone number format.', 'Неверный формат номера телефона.'],
            ['errors.network', 'errors', 'Şəbəkə problemi. Xahiş edirik, internet bağlantınızı yoxlayın.', 'Network problem. Please check your internet connection.', 'Проблема с сетью. Проверьте подключение к интернету.'],
            ['errors.phone_taken', 'errors', 'Bu telefon nömrəsi artıq qeydiyyatdadır.', 'This phone number is already registered.', 'Этот номер уже зарегистрирован.'],
            ['errors.validation', 'errors', 'Daxil etdiyiniz məlumatda səhv var.', 'There is a problem with the data you entered.', 'В введённых данных есть ошибка.'],
            ['errors.unauthorized', 'errors', 'Giriş icazəniz yoxdur. Yenidən daxil olun.', 'You are not authorized. Please log in again.', 'Нет доступа. Войдите снова.'],
            ['errors.forbidden', 'errors', 'İcazə yoxdur. Hesabınızla bağlı problem ola bilər.', 'Access denied. There may be an issue with your account.', 'Доступ запрещён. Возможна проблема с аккаунтом.'],
            ['errors.not_found', 'errors', 'Tələb olunan resurs tapılmadı.', 'The requested resource was not found.', 'Запрошенный ресурс не найден.'],
            ['errors.server', 'errors', 'Serverdə problem baş verdi. Zəhmət olmasa yenidən cəhd edin.', 'A server error occurred. Please try again.', 'Ошибка сервера. Попробуйте ещё раз.'],
            ['errors.unavailable', 'errors', 'Xidmət müvəqqəti olaraq əlçatmazdır. Bir az sonra yenidən yoxlayın.', 'The service is temporarily unavailable. Please try later.', 'Сервис временно недоступен. Попробуйте позже.'],
            ['errors.generic', 'errors', 'Gözlənilməz xəta baş verdi. Zəhmət olmasa yenidən cəhd edin.', 'An unexpected error occurred. Please try again.', 'Произошла непредвиденная ошибка. Попробуйте ещё раз.'],
            ['sub.plans_title', 'sub', 'Abunəlik paketləri', 'Subscription plans', 'Тарифные планы'],
            ['sub.plans_subtitle', 'sub', 'Quizzo-dan tam yararlanmaq üçün aylıq paketlərdən birini seç — quiz oyna, endirim kuponları qazan. 🎯', 'Pick a monthly plan to get the most out of Quizzo — play quizzes and win discount coupons. 🎯', 'Выберите месячный тариф, чтобы пользоваться Quizzo полностью — играйте и получайте купоны. 🎯'],
            ['sub.no_plans', 'sub', 'Hələ satışda paket yoxdur', 'No plans on sale yet', 'Тарифов пока нет'],
            ['sub.no_plans_desc', 'sub', 'Bir az sonra yenidən yoxlayın.', 'Please check back soon.', 'Загляните позже.'],
            ['sub.subscribe', 'sub', 'Abunə ol', 'Subscribe', 'Оформить'],
            ['sub.login_and_subscribe', 'sub', 'Daxil ol və abunə ol', 'Log in & subscribe', 'Войти и оформить'],
            ['sub.activate', 'sub', 'Aktivləşdir', 'Activate', 'Активировать'],
            ['sub.current_plan_badge', 'sub', 'Cari paketin', 'Your current plan', 'Ваш тариф'],
            ['sub.trial_badge', 'sub', 'Sınaq', 'Trial', 'Пробный'],
            ['sub.is_active_label', 'sub', 'Aktivdir', 'Active', 'Активен'],
            ['sub.wait', 'sub', 'Gözləyin...', 'Please wait...', 'Подождите...'],
            ['sub.free', 'sub', 'Pulsuz', 'Free', 'Бесплатно'],
            ['sub.free_trial', 'sub', 'Pulsuz sınaq', 'Free trial', 'Бесплатный период'],
            ['sub.period_month', 'sub', 'ay', 'month', 'мес.'],
            ['sub.period_year', 'sub', 'il', 'year', 'год'],
            ['sub.period_days', 'sub', '{count} gün', '{count} days', '{count} дн.'],
            ['sub.feature_daily', 'sub', 'Gündəlik quiz: {value}', 'Quizzes per day: {value}', 'Квизов в день: {value}'],
            ['sub.feature_monthly', 'sub', 'Aylıq kupon: {value}', 'Coupons per month: {value}', 'Купонов в месяц: {value}'],
            ['sub.my_title', 'sub', '💳 Abunəliyim', '💳 My subscription', '💳 Моя подписка'],
            ['sub.current_plan', 'sub', 'Cari paket', 'Current plan', 'Текущий тариф'],
            ['sub.no_plan', 'sub', 'Paket seçilməyib', 'No plan selected', 'Тариф не выбран'],
            ['sub.status_active', 'sub', 'Aktiv', 'Active', 'Активна'],
            ['sub.status_inactive', 'sub', 'Passiv', 'Inactive', 'Неактивна'],
            ['sub.ends_at', 'sub', 'Bitmə tarixi', 'Expires on', 'Действует до'],
            ['sub.usage_quizzes', 'sub', 'Bu gün oynanılan quiz', 'Quizzes played today', 'Квизов сыграно сегодня'],
            ['sub.usage_coupons', 'sub', 'Bu ay qazanılan kupon', 'Coupons earned this month', 'Купонов получено за месяц'],
            ['sub.saved_card', 'sub', '💳 Yadda saxlanılan kart: {mask}', '💳 Saved card: {mask}', '💳 Сохранённая карта: {mask}'],
            ['sub.auto_renew', 'sub', '🔄 Avtomatik yenilənmə: {state}', '🔄 Auto-renewal: {state}', '🔄 Автопродление: {state}'],
            ['sub.on', 'sub', 'Açıq', 'On', 'Вкл'],
            ['sub.off', 'sub', 'Bağlı', 'Off', 'Выкл'],
            ['sub.remove_card', 'sub', 'Kartı sil', 'Remove card', 'Удалить карту'],
            ['sub.pending_title', 'sub', '⏳ Ödənilməmiş sorğunuz var', '⏳ You have an unpaid request', '⏳ Есть неоплаченный запрос'],
            ['sub.pending_desc', 'sub', '{plan} — {amount} {currency} ({periods} dövr)', '{plan} — {amount} {currency} ({periods} periods)', '{plan} — {amount} {currency} ({periods} периодов)'],
            ['sub.complete_payment', 'sub', 'Ödənişi tamamla', 'Complete payment', 'Завершить оплату'],
            ['sub.cancel_request', 'sub', 'Sorğunu ləğv et', 'Cancel request', 'Отменить запрос'],
            ['sub.change_plan', 'sub', 'Paketi dəyiş / uzat', 'Change / extend plan', 'Сменить / продлить тариф'],
            ['sub.choose_plan', 'sub', 'Paket seç', 'Choose a plan', 'Выберите тариф'],
            ['sub.save_card', 'sub', 'Kartı yadda saxla', 'Save my card', 'Сохранить карту'],
            ['sub.history', 'sub', '📜 Tarixçə', '📜 History', '📜 История'],
            ['sub.th_plan', 'sub', 'Paket', 'Plan', 'Тариф'],
            ['sub.th_amount', 'sub', 'Məbləğ', 'Amount', 'Сумма'],
            ['sub.th_start', 'sub', 'Başlanğıc', 'Start', 'Начало'],
            ['sub.th_end', 'sub', 'Bitmə', 'End', 'Окончание'],
            ['sub.req_pending', 'sub', 'Gözləyir', 'Pending', 'Ожидает'],
            ['sub.req_approved', 'sub', 'Təsdiqlənib', 'Approved', 'Подтверждён'],
            ['sub.req_rejected', 'sub', 'Rədd edilib', 'Rejected', 'Отклонён'],
            ['sub.req_cancelled', 'sub', 'Ləğv edilib', 'Cancelled', 'Отменён'],
            ['sub.pay_success', 'sub', 'Ödəniş uğurlu oldu — paketiniz aktivdir! 🎉', 'Payment successful — your plan is active! 🎉', 'Оплата прошла — тариф активен! 🎉'],
            ['sub.pay_failed', 'sub', 'Bank ödənişi təsdiqləmədi. Yenidən cəhd edə bilərsiniz.', 'The bank declined the payment. You can try again.', 'Банк отклонил платёж. Попробуйте ещё раз.'],
            ['sub.pay_error', 'sub', 'Ödəniş yoxlanıla bilmədi. Bir az sonra yenidən baxın.', 'The payment could not be verified. Please check back later.', 'Не удалось проверить платёж. Загляните позже.'],
            ['sub.plan_activated', 'sub', 'Paket aktivləşdirildi.', 'Plan activated.', 'Тариф активирован.'],
            ['sub.claim_ready', 'sub', '🎉 Gözləyən kuponunuz hazırdır: {code}', '🎉 Your pending coupon is ready: {code}', '🎉 Ваш купон готов: {code}'],
            ['sub.claim_needed', 'sub', 'Kuponu almaq üçün abunəlik lazımdır.', 'A subscription is required to claim the coupon.', 'Для получения купона нужна подписка.'],
            ['sub.coupon_ready', 'sub', '🎉 Kuponunuz hazırdır: {code}', '🎉 Your coupon is ready: {code}', '🎉 Ваш купон готов: {code}'],
            ['sub.session_linked', 'sub', 'Nəticəniz hesabınıza bağlandı.', 'Your result has been linked to your account.', 'Результат привязан к вашему аккаунту.'],
            ['sub.claim_failed', 'sub', 'Sessiyanı hesaba bağlamaq mümkün olmadı.', 'Could not link the session to your account.', 'Не удалось привязать сессию к аккаунту.'],
            ['store.address_title', 'store', '📍 Ünvan', '📍 Address', '📍 Адрес'],
            ['store.map_title', 'store', 'xəritə', 'map', 'карта'],
            ['store.open_in_maps', 'store', 'Google Maps-də aç →', 'Open in Google Maps →', 'Открыть в Google Maps →'],
        ];
    }
}
